test sonar

diff --git a/.github/workflows/parameter_replication.yml b/.github/workflows/parameter_replication.yml
--- a/.github/workflows/parameter_replication.yml
+++ b/.github/workflows/parameter_replication.yml
@@ -40,23 +40,34 @@ jobs:
               -Dsonar.organization=girishadb
               -Dsonar.projectKey=AWS-Parameter
               -Dsonar.sources=.
-              -Dsonar.qualitygate.wait=true
-              -Dsonar.qualitygate.timeout=300
+      - name: SonarQube Quality Gate check
+        id: sonarqube-quality-gate-check
+        uses: SonarSource/sonarqube-quality-gate-action@v1
+        # Force to fail step after a specific time.
+        timeout-minutes: 5
+
+      - name: Set Job Outcome
+        if: steps.sonarqube-quality-gate-check.outputs.quality-gate-status == 'FAILED'
+        run: exit 1
+
+      - name: "Example show SonarQube Quality Gate Status value"
+        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}
+    
               
         
-      - name: Check SonarQube Analysis Result
-        run: |
-          sonar_status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=AWS-Parameter" | jq -r '.projectStatus.status')
-          echo "SonarQube Analysis Result: $sonar_status"
-          echo "::set-output name=sonar_status::$sonar_status"
+      # - name: Check SonarQube Analysis Result
+      #   run: |
+      #     sonar_status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=AWS-Parameter" | jq -r '.projectStatus.status')
+      #     echo "SonarQube Analysis Result: $sonar_status"
+      #     echo "::set-output name=sonar_status::$sonar_status"
          
-      - name: Fail if SonarQube Analysis Failed
-        if: always()
-        run: |
-          if [ "${{ steps.sonarqube-scan.outputs.sonar_status }}" != "OK" ]; then
-            echo "SonarQube analysis failed."
-            exit 1
-          fi
+      # - name: Fail if SonarQube Analysis Failed
+      #   if: always()
+      #   run: |
+      #     if [ "${{ steps.sonarqube-scan.outputs.sonar_status }}" != "OK" ]; then
+      #       echo "SonarQube analysis failed."
+      #       exit 1
+      #     fi
           
               
 # jobs:
