test

diff --git a/.github/workflows/parameter_replication.yml b/.github/workflows/parameter_replication.yml
--- a/.github/workflows/parameter_replication.yml
+++ b/.github/workflows/parameter_replication.yml
@@ -105,10 +105,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Check integration-test result and set workflow status
-        if: ${{ needs.integration-test.result == 'success' }}
+        if: ${{ needs.integration-test.result != 'success' }}
         run: |
-          echo "Integration test Success"
-          exit 0
+          echo "Integration test failed"
+          exit 1
 
 # jobs:
 #     run-tests:
