check terraform

diff --git a/.github/workflows/parameter_replication.yml b/.github/workflows/parameter_replication.yml
--- a/.github/workflows/parameter_replication.yml
+++ b/.github/workflows/parameter_replication.yml
@@ -19,106 +19,127 @@ env:
     # DEST_SHORT_NAME: ${{vars.DEST_SHORT_NAME}}
     TF_VAR_access_key: ${{ secrets.ACCESS_KEY }}
     TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
-    
+    GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
+    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
 jobs:
-  integration-test:
-    if: ${{ github.event.pull_request.merged == true }}
-    runs-on: [ ubuntu-latest ]
-    defaults:
-      run:
-        working-directory: ${{ github.workspace }}
-    
-    steps:
-      - name: Check out repository code
-        uses: actions/checkout@v2
-
-      - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          terraform_version: 1.0.5
-      - name: Install AWS CLI
-        run: |
-          sudo apt-get install python3-pip -y
-          pip3 install awscli --upgrade --user
-
-      - name: Configure AWS Credentials
-        
-        run: |
-          aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY }}
-          aws configure set aws_secret_access_key ${{ secrets.SECRET_KEY }}
-          aws configure set default.region ${{ vars.AWS_REGION }}
-
-      # - name: Terraform deploy
-      #   run: |
-      #     cd src/Terraform
-      #     terraform init
-      #     terraform plan
-      #     terraform apply --auto-approve
-
-      # - name: Set up Python 3.11
-      #   uses: actions/setup-python@v4
-      #   with:
-      #     python-version: 3.11
-      # - name: Install dependencies for integration testing
-      #   run: |
-      #     cd src/python/tests/integration
-      #     python -m pip install --upgrade pip
-      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-
-      # - name: Run integration tests
-      #   run: |
-      #     cd src/python/tests/integration
-      #     python3 integration.py
-
-  integration-test-resources-cleanup:
-    needs: integration-test
-    if: always() && (github.event.pull_request.merged == true)
-    runs-on: [ ubuntu-latest ]
-    defaults:
-      run:
-        working-directory: ${{ github.workspace }}/src/Terraform
-  
-    steps:
-      - name: Check out repository code
-        uses: actions/checkout@v2
-  
-      - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          terraform_version: 1.0.5
-      - name: Install AWS CLI
-        run: |
-          sudo apt-get install python3-pip -y
-          pip3 install awscli --upgrade --user
-  
-      - name: Configure AWS Credentials
-        run: |
-          aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY }}
-          aws configure set aws_secret_access_key ${{ secrets.SECRET_KEY }}
-          aws configure set default.region ${{ vars.AWS_REGION }}
-  
-      - name: Terraform Init
-        run: terraform init
-      - name: Terraform Destroy --auto-approve
-        run: |
-          terraform destroy -target aws_cloudwatch_log_group.event_rule_log_group
-
-  integration-test-status:
-    
-    needs: [integration-test, integration-test-resources-cleanup]
-    if: always() && (github.event.pull_request.merged == true)
+  DemoSonarCloudSCan:
     runs-on: ubuntu-latest
     steps:
-      - name: Check integration-test result and set workflow status
-        if: ${{ needs.integration-test.result == 'success' && needs.integration-test-resources-cleanup.result == 'success' }}
-        run: |
-          echo "Integration test Success"
-          exit 0
-      - name: Set workflow status for failed tests
-        if: ${{ needs.integration-test.result != 'success' || needs.integration-test-resources-cleanup.result != 'success' }}
-        run: |
-          echo "Integration test Failed"
-          exit 1
+      - uses: actions/checkout@v3
+        with:
+            fetch-depth: 0
+      - name: SonarCloud Scan
+        uses: sonarsource/sonarcloud-github-action@master
+        env:
+            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
+            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        with:
+          args: >
+              -Dsonar.organization=girishadb
+              -Dsonar.projectKey=AWS-Parameter
+              -Dsonar.sources=.
+
+    
+# jobs:
+#   integration-test:
+#     if: ${{ github.event.pull_request.merged == true }}
+#     runs-on: [ ubuntu-latest ]
+#     defaults:
+#       run:
+#         working-directory: ${{ github.workspace }}
+    
+#     steps:
+#       - name: Check out repository code
+#         uses: actions/checkout@v2
+
+#       - name: Set up Terraform
+#         uses: hashicorp/setup-terraform@v1
+#         with:
+#           terraform_version: 1.0.5
+#       - name: Install AWS CLI
+#         run: |
+#           sudo apt-get install python3-pip -y
+#           pip3 install awscli --upgrade --user
+
+#       - name: Configure AWS Credentials
+        
+#         run: |
+#           aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY }}
+#           aws configure set aws_secret_access_key ${{ secrets.SECRET_KEY }}
+#           aws configure set default.region ${{ vars.AWS_REGION }}
+
+#       # - name: Terraform deploy
+#       #   run: |
+#       #     cd src/Terraform
+#       #     terraform init
+#       #     terraform plan
+#       #     terraform apply --auto-approve
+
+#       # - name: Set up Python 3.11
+#       #   uses: actions/setup-python@v4
+#       #   with:
+#       #     python-version: 3.11
+#       # - name: Install dependencies for integration testing
+#       #   run: |
+#       #     cd src/python/tests/integration
+#       #     python -m pip install --upgrade pip
+#       #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+
+#       # - name: Run integration tests
+#       #   run: |
+#       #     cd src/python/tests/integration
+#       #     python3 integration.py
+
+#   integration-test-resources-cleanup:
+#     needs: integration-test
+#     if: always() && (github.event.pull_request.merged == true)
+#     runs-on: [ ubuntu-latest ]
+#     defaults:
+#       run:
+#         working-directory: ${{ github.workspace }}/src/Terraform
+  
+#     steps:
+#       - name: Check out repository code
+#         uses: actions/checkout@v2
+  
+#       - name: Set up Terraform
+#         uses: hashicorp/setup-terraform@v1
+#         with:
+#           terraform_version: 1.0.5
+#       - name: Install AWS CLI
+#         run: |
+#           sudo apt-get install python3-pip -y
+#           pip3 install awscli --upgrade --user
+  
+#       - name: Configure AWS Credentials
+#         run: |
+#           aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY }}
+#           aws configure set aws_secret_access_key ${{ secrets.SECRET_KEY }}
+#           aws configure set default.region ${{ vars.AWS_REGION }}
+  
+#       - name: Terraform Init
+#         run: terraform init
+#       - name: Terraform Destroy --auto-approve
+#         run: |
+#           terraform destroy -target aws_cloudwatch_log_group.event_rule_log_group
+
+#   integration-test-status:
+    
+#     needs: [integration-test, integration-test-resources-cleanup]
+#     if: always() && (github.event.pull_request.merged == true)
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Check integration-test result and set workflow status
+#         if: ${{ needs.integration-test.result == 'success' && needs.integration-test-resources-cleanup.result == 'success' }}
+#         run: |
+#           echo "Integration test Success"
+#           exit 0
+#       - name: Set workflow status for failed tests
+#         if: ${{ needs.integration-test.result != 'success' || needs.integration-test-resources-cleanup.result != 'success' }}
+#         run: |
+#           echo "Integration test Failed"
+#           exit 1
 
 
           
